import { test, expect } from '@playwright/test';

test('Registrar todos los materiales', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('ldiegobonillaib@gmail.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('D');
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('Diego12345');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Inventario' }).click();
  await page.getByRole('button', { name: 'Agregar Inventario' }).click();
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="name"]').press('CapsLock');
  await page.locator('input[name="name"]').fill('T');
  await page.locator('input[name="name"]').press('CapsLock');
  await page.locator('input[name="name"]').fill('Tela de europa');
  await page.locator('textarea[name="description"]').click();
  await page.locator('textarea[name="description"]').press('CapsLock');
  await page.locator('textarea[name="description"]').fill('T');
  await page.locator('textarea[name="description"]').press('CapsLock');
  await page.getByText('T', { exact: true }).fill('Tela suave traida desde españa');
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('');
  await page.getByRole('spinbutton').press('ArrowLeft');
  await page.getByRole('spinbutton').fill('100');
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.getByRole('button', { name: 'Sí' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await expect(page.locator('tbody')).toContainText('Tela de europa');
});


test('Registrar material con datos inválidos', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('ldiegobonillaib@gmail.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('D');
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('Diego12345');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Inventario' }).click();
  await page.getByRole('button', { name: 'Agregar Inventario' }).click();
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.locator('input[name="name"]').click();
  await page.locator('input[name="name"]').press('CapsLock');
  await page.locator('input[name="name"]').fill('N');
  await page.locator('input[name="name"]').press('CapsLock');
  await page.locator('input[name="name"]').fill('');
  await page.locator('input[name="name"]').press('CapsLock');
  await page.locator('input[name="name"]').fill('T');
  await page.locator('input[name="name"]').press('CapsLock');
  await page.locator('input[name="name"]').fill('Tela brush');
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.locator('textarea[name="description"]').click();
  await page.locator('textarea[name="description"]').press('CapsLock');
  await page.locator('textarea[name="description"]').fill('T');
  await page.locator('textarea[name="description"]').press('CapsLock');
  await page.getByText('T', { exact: true }).fill('Tela para camisas');
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').press('ArrowLeft');
  await page.getByRole('spinbutton').fill('10');
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.getByRole('button', { name: 'Sí' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
});