import { test, expect } from '@playwright/test';

test('Crear nuevo producto de ropa y accesorios', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('ldiegobonillaib@gmail.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('D');
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('Diego12345');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Productos' }).click();
  await page.getByRole('button', { name: 'Agregar producto' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre' }).fill('C');
  await page.getByRole('textbox', { name: 'Nombre' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre' }).fill('Camisa');
  await page.getByRole('textbox', { name: 'Descripción' }).click();
  await page.getByRole('textbox', { name: 'Descripción' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Descripción' }).fill('C');
  await page.getByRole('textbox', { name: 'Descripción' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Descripción' }).fill('Camisa polov');
  await page.getByRole('textbox', { name: 'Color' }).click();
  await page.getByRole('textbox', { name: 'Color' }).fill('verde');
  await page.getByRole('textbox', { name: 'Tipo de material' }).click();
  await page.getByRole('textbox', { name: 'Tipo de material' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tipo de material' }).fill('B');
  await page.getByRole('textbox', { name: 'Tipo de material' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tipo de material' }).fill('Broche');
  await page.getByRole('spinbutton', { name: 'Precio' }).click();
  await page.getByRole('spinbutton', { name: 'Precio' }).fill('030000');
  await page.getByRole('spinbutton', { name: 'Cantidad' }).click();
  await page.getByRole('spinbutton', { name: 'Cantidad' }).fill('040');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('camisaVerde.png');
  await page.getByRole('textbox', { name: 'Talla' }).click();
  await page.getByRole('textbox', { name: 'Talla' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Talla' }).fill('L');
  await page.getByRole('textbox', { name: 'Talla' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tipo de ropa' }).click();
  await page.getByRole('textbox', { name: 'Tipo de ropa' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tipo de ropa' }).fill('P');
  await page.getByRole('textbox', { name: 'Tipo de ropa' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tipo de ropa' }).fill('Polo');
  await page.getByLabel('Género').selectOption('Masculino');
  await page.getByRole('button', { name: 'Guardar producto' }).click();
  await page.getByRole('button', { name: 'Sí' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
});

test('Validar formulario de producto', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('ldiegobonillaib@gmail.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('D');
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('Diego12345');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByText('Productos').click();
  await page.getByRole('button', { name: 'Agregar producto' }).click();
  await page.getByRole('button', { name: 'Guardar producto' }).click();
  await expect(page.locator('#swal2-title')).toContainText('Formulario inválido');
  await expect(page.locator('#swal2-html-container')).toContainText('El nombre es obligatorio.');
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre' }).fill('D');
  await page.getByRole('textbox', { name: 'Nombre' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre' }).fill('');
  await page.getByRole('textbox', { name: 'Nombre' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre' }).fill('C');
  await page.getByRole('textbox', { name: 'Nombre' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre' }).fill('Camisa');
  await page.getByLabel('Categoría').selectOption('1');
  await page.getByRole('textbox', { name: 'Descripción' }).click();
  await page.getByRole('textbox', { name: 'Descripción' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Descripción' }).fill('CA');
  await page.getByRole('textbox', { name: 'Descripción' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Descripción' }).fill('Camisa para silla');
  await page.getByRole('textbox', { name: 'Color' }).click();
  await page.getByRole('textbox', { name: 'Color' }).fill('verdee');
  await page.getByRole('textbox', { name: 'Tipo de material' }).click();
  await page.getByRole('textbox', { name: 'Tipo de material' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tipo de material' }).fill('L');
  await page.getByRole('textbox', { name: 'Tipo de material' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tipo de material' }).fill('Lisa');
  await page.getByRole('textbox', { name: 'Tipo de material' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tipo de material' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tipo de material' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tipo de material' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Tipo de material' }).fill('Lisa');
  await page.getByRole('textbox', { name: 'Tipo de material' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tipo de material' }).fill('TLisa');
  await page.getByRole('textbox', { name: 'Tipo de material' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Tipo de material' }).fill('Tela Lisa');
  await page.getByRole('spinbutton', { name: 'Precio' }).click();
  await page.getByRole('spinbutton', { name: 'Precio' }).fill('04000');
  await page.getByRole('spinbutton', { name: 'Cantidad' }).click();
  await page.getByRole('spinbutton', { name: 'Cantidad' }).fill('05');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('camisaVerde.png');
  await page.getByRole('spinbutton', { name: 'Altura' }).click();
  await page.getByRole('spinbutton', { name: 'Altura' }).fill('020');
  await page.getByRole('spinbutton', { name: 'Largo' }).click();
  await page.getByRole('spinbutton', { name: 'Largo' }).fill('030');
  await page.getByRole('spinbutton', { name: 'Ancho' }).click();
  await page.getByRole('spinbutton', { name: 'Ancho' }).fill('012');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles([]);
  await page.getByRole('button', { name: 'Guardar producto' }).click();
  await expect(page.locator('#swal2-html-container')).toContainText('Debes seleccionar una imagen.');
  await page.getByRole('button', { name: 'Aceptar' }).click();

});