import { test, expect } from '@playwright/test';

test('registro exitoso de un nuevo usuario', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.getByRole('link', { name: 'Crear cuenta' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().press('CapsLock');
  await page.getByRole('textbox').first().fill('D');
  await page.getByRole('textbox').first().press('CapsLock');
  await page.getByRole('textbox').first().fill('Diego');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('B');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('Bonilla ');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('Bonilla B');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('Bonilla Baltodano');
  await page.locator('input[type="date"]').fill('2002-06-15');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('88888888');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('ldieegobonilla901@gmail.com');
  await page.getByRole('combobox').selectOption('Masculino');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).press('CapsLock');
  await page.getByRole('textbox').nth(5).fill('D');
  await page.getByRole('textbox').nth(5).press('CapsLock');
  await page.getByRole('textbox').nth(5).fill('Diego12345');
  await page.locator('input[type="password"]').nth(1).click();
  await page.locator('input[type="password"]').nth(1).press('CapsLock');
  await page.locator('input[type="password"]').nth(1).fill('D');
  await page.locator('input[type="password"]').nth(1).press('CapsLock');
  await page.locator('input[type="password"]').nth(1).fill('Diego12345');
  await page.locator('.grid-3 > div > .input').first().click();
  await page.locator('.grid-3 > div > .input').first().press('CapsLock');
  await page.locator('.grid-3 > div > .input').first().fill('S');
  await page.locator('.grid-3 > div > .input').first().press('CapsLock');
  await page.locator('.grid-3 > div > .input').first().fill('San jose');
  await page.locator('.grid-3 > div:nth-child(2) > .input').click();
  await page.locator('.grid-3 > div:nth-child(2) > .input').fill('central');
  await page.locator('.grid-3 > div:nth-child(3) > .input').click();
  await page.locator('.grid-3 > div:nth-child(3) > .input').fill('carmen');
  await page.locator('textarea').click();
  await page.locator('textarea').fill('de la iglesia 100 metros al sur');
  await page.getByRole('button', { name: 'Crear cuenta' }).click();
  await expect(page.locator('#swal2-title')).toContainText('¡Cuenta creada!');
  await expect(page.locator('#swal2-html-container')).toContainText('Usuario registrado correctamente');
  await page.getByRole('button', { name: 'Aceptar' }).click();
});


test('Error de constraseña incorrecta/no coincide', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.getByRole('link', { name: 'Crear cuenta' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().fill('d');
  await page.getByRole('textbox').first().press('CapsLock');
  await page.getByRole('textbox').first().fill('D');
  await page.getByRole('textbox').first().press('CapsLock');
  await page.getByRole('textbox').first().fill('Diego');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('B');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('Bonilla ');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('Bonilla B');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('Bonilla Baltodano');
  await page.locator('input[type="date"]').fill('2002-06-15');
  await page.locator('div').filter({ hasText: /^Teléfono$/ }).click();
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('88888888');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('ldiegobonillaib@gmail.com');
  await page.getByRole('combobox').selectOption('Masculino');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('diego12345');
  await page.getByRole('textbox').nth(5).press('CapsLock');
  await page.getByRole('textbox').nth(5).fill('diego12345A');
  await page.getByRole('textbox').nth(5).press('CapsLock');
  await page.locator('input[type="password"]').nth(1).click();
  await page.locator('input[type="password"]').nth(1).fill('dieego12345');
  await page.locator('input[type="password"]').nth(1).press('CapsLock');
  await page.locator('input[type="password"]').nth(1).fill('dieego12345A');
  await page.locator('input[type="password"]').nth(1).press('CapsLock');
  await page.locator('.grid-3 > div > .input').first().click();
  await page.locator('.grid-3 > div > .input').first().press('CapsLock');
  await page.locator('.grid-3 > div > .input').first().fill('L');
  await page.locator('.grid-3 > div > .input').first().press('CapsLock');
  await page.locator('.grid-3 > div > .input').first().fill('Limon');
  await page.locator('.grid-3 > div:nth-child(2) > .input').click();
  await page.locator('.grid-3 > div:nth-child(2) > .input').fill('pococic');
  await page.locator('.grid-3 > div:nth-child(3) > .input').click();
  await page.locator('.grid-3 > div:nth-child(3) > .input').fill('cariari');
  await page.locator('textarea').click();
  await page.locator('textarea').fill('campo cinco este');
  await page.getByRole('button', { name: 'Crear cuenta' }).click();
  await expect(page.locator('#swal2-title')).toContainText('Formulario inválido');
  await expect(page.locator('#swal2-html-container')).toContainText('Las contraseñas no coinciden.');
  await page.getByRole('button', { name: 'Aceptar' }).click();
});

test('Error en tratar de registrar un usuario con un correo ya existente', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.getByRole('link', { name: 'Crear cuenta' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().press('CapsLock');
  await page.getByRole('textbox').first().fill('D');
  await page.getByRole('textbox').first().press('CapsLock');
  await page.getByRole('textbox').first().fill('Diego');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('B');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('Bonilla ');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('Bonilla B');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('Bonilla Baltodano');
  await page.locator('input[type="date"]').fill('2002-06-15');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('8888888');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('ldieegobonilla901@gmail.com');
  await page.getByRole('combobox').selectOption('Masculino');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).fill('diego');
  await page.getByRole('textbox').nth(5).press('CapsLock');
  await page.getByRole('textbox').nth(5).fill('diegoB');
  await page.getByRole('textbox').nth(5).press('CapsLock');
  await page.getByRole('textbox').nth(5).fill('diegoB007');
  await page.locator('input[type="password"]').nth(1).click();
  await page.locator('input[type="password"]').nth(1).fill('diego');
  await page.locator('input[type="password"]').nth(1).press('CapsLock');
  await page.locator('input[type="password"]').nth(1).fill('diegoB');
  await page.locator('input[type="password"]').nth(1).press('CapsLock');
  await page.locator('input[type="password"]').nth(1).fill('diegoB007');
  await page.getByRole('textbox').nth(5).click();
  await page.locator('.grid-3 > div > .input').first().fill('limon');
  await page.locator('.grid-3 > div:nth-child(2) > .input').fill('pococi');
  await page.getByText('ProvinciaCantónDistrito').click();
  await page.locator('.grid-3 > div:nth-child(2) > .input').fill('pococic');
  await page.locator('.grid-3 > div:nth-child(3) > .input').click();
  await page.locator('.grid-3 > div:nth-child(3) > .input').fill('carari');
  await page.locator('textarea').click();
  await page.locator('textarea').fill('campo cinco');
  await page.getByRole('button', { name: 'Crear cuenta' }).click();
  await expect(page.locator('#swal2-title')).toContainText('No se pudo registrar');
  await expect(page.locator('#swal2-html-container')).toContainText('El correo ya está registrado');
  await expect(page.getByLabel('No se pudo registrar')).toContainText('');
  await page.getByRole('button', { name: 'Aceptar' }).click();
});


test('El sistema no debe de guardar al ingresar datos vacíos en el formulario de registro.', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.getByRole('link', { name: 'Crear cuenta' }).click();
  await page.getByRole('button', { name: 'Crear cuenta' }).click();
  await expect(page.locator('#swal2-html-container')).toContainText('El nombre es obligatorio.');
  await expect(page.locator('#swal2-title')).toContainText('Formulario inválido');
});


test('El sistema debe validar una contraseña segura, que tenga por lo menos 8 dígitos, letras, números, una minúscula y una mayúscula.', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.getByRole('link', { name: 'Crear cuenta' }).click();
  await page.getByRole('textbox').first().click();
  await page.getByRole('textbox').first().press('CapsLock');
  await page.getByRole('textbox').first().fill('D');
  await page.getByRole('textbox').first().press('CapsLock');
  await page.getByRole('textbox').first().fill('Diego');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('B');
  await page.getByRole('textbox').nth(1).press('CapsLock');
  await page.getByRole('textbox').nth(1).fill('Bonilla');
  await page.locator('input[type="date"]').fill('2002-08-15');
  await page.getByRole('textbox').nth(3).click();
  await page.getByRole('textbox').nth(3).fill('88888888');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('ldiegobonilla22@gmail.com');
  await page.getByRole('combobox').selectOption('Masculino');
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('textbox').nth(5).press('CapsLock');
  await page.getByRole('textbox').nth(5).fill('D');
  await page.getByRole('textbox').nth(5).press('CapsLock');
  await page.getByRole('textbox').nth(5).fill('Diego');
  await page.locator('input[type="password"]').nth(1).click();
  await page.locator('input[type="password"]').nth(1).press('CapsLock');
  await page.locator('input[type="password"]').nth(1).fill('D');
  await page.locator('input[type="password"]').nth(1).press('CapsLock');
  await page.locator('input[type="password"]').nth(1).fill('Diego');
  await page.locator('.grid-3 > div > .input').first().click();
  await page.locator('.grid-3 > div > .input').first().press('CapsLock');
  await page.locator('.grid-3 > div > .input').first().fill('L');
  await page.locator('.grid-3 > div > .input').first().press('CapsLock');
  await page.locator('.grid-3 > div > .input').first().fill('Limon');
  await page.locator('.grid-3 > div:nth-child(2) > .input').click();
  await page.locator('.grid-3 > div:nth-child(2) > .input').press('CapsLock');
  await page.locator('.grid-3 > div:nth-child(2) > .input').fill('P');
  await page.locator('.grid-3 > div:nth-child(2) > .input').press('CapsLock');
  await page.locator('.grid-3 > div:nth-child(2) > .input').fill('Pococi');
  await page.locator('.grid-3 > div:nth-child(3) > .input').click();
  await page.locator('.grid-3 > div:nth-child(2) > .input').press('CapsLock');
  await page.locator('.grid-3 > div:nth-child(3) > .input').fill('C');
  await page.locator('.grid-3 > div:nth-child(3) > .input').press('CapsLock');
  await page.locator('.grid-3 > div:nth-child(3) > .input').fill('Cariari');
  await page.locator('textarea').click();
  await page.locator('textarea').press('CapsLock');
  await page.locator('textarea').fill('C');
  await page.locator('textarea').press('CapsLock');
  await page.getByText('C', { exact: true }).fill('Campo cinco');
  await page.getByRole('button', { name: 'Crear cuenta' }).click();
  await expect(page.locator('#swal2-html-container')).toContainText('La contraseña debe tener al menos 8 caracteres.');
  await expect(page.locator('#swal2-title')).toContainText('Formulario inválido');
  await page.getByRole('button', { name: 'Aceptar' }).click();
});

