import { test, expect } from '@playwright/test';

test('Test para actualizar producto ', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('ldiegobonillaib@gmail.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('D');
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('Diego12345');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Productos' }).click();
  await page.getByRole('button', { name: 'Editar' }).nth(4).click();
  await page.getByRole('textbox', { name: 'Nombre' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).fill('Camisa verde');
  await page.getByRole('textbox', { name: 'Descripción' }).click();
  await page.getByRole('textbox', { name: 'Descripción' }).fill('Camisa polo');
  await page.getByRole('spinbutton', { name: 'Precio' }).click();
  await page.getByRole('spinbutton', { name: 'Precio' }).fill('300000');
  await page.getByRole('spinbutton', { name: 'Cantidad' }).click();
  await page.getByRole('spinbutton', { name: 'Cantidad' }).fill('43');
  await page.getByRole('textbox', { name: 'Talla' }).click();
  await page.getByRole('textbox', { name: 'Talla' }).fill('');
  await page.getByRole('textbox', { name: 'Talla' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Talla' }).fill('XL');
  await page.getByRole('textbox', { name: 'Talla' }).press('CapsLock');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.getByRole('button', { name: 'Sí' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
});

test('Test de validación de formulario para actualizar producto', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('ldiegobonillaib@gmail.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('D');
  await page.locator('input[type="password"]').press('CapsLock');
  await page.locator('input[type="password"]').fill('Diego12345');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByText('Productos').click();
  await page.getByRole('button', { name: 'Editar' }).nth(4).click();
  await page.getByRole('textbox', { name: 'Nombre' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).fill('');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre' }).fill('C');
  await page.getByRole('textbox', { name: 'Nombre' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Nombre' }).fill('Camisa');
  await page.getByRole('textbox', { name: 'Descripción' }).click();
  await page.getByRole('textbox', { name: 'Color' }).click();
  await page.getByRole('textbox', { name: 'Color' }).fill('');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('textbox', { name: 'Color' }).click();
  await page.getByRole('textbox', { name: 'Color' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Color' }).fill('V');
  await page.getByRole('textbox', { name: 'Color' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Color' }).fill('Verde');
  await page.getByRole('textbox', { name: 'Tipo de material' }).click();
  await page.getByRole('textbox', { name: 'Tipo de material' }).fill('');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('textbox', { name: 'Tipo de material' }).click();
  await page.getByRole('textbox', { name: 'Tipo de material' }).fill('lisa');
  await page.getByText('Selecciona una imagen (opcional)Quitar imagen').click();
  await page.getByText('Selecciona una imagen (opcional)Quitar imagen').click();
  await page.getByRole('textbox', { name: 'Talla' }).click();
  await page.getByRole('textbox', { name: 'Talla' }).fill('');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('textbox', { name: 'Talla' }).click();
  await page.getByRole('textbox', { name: 'Talla' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Talla' }).fill('XL');
  await page.getByRole('textbox', { name: 'Talla' }).press('CapsLock');
  await page.getByRole('button', { name: 'Guardar cambios' }).click();
  await page.getByRole('button', { name: 'Sí' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
});