import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('cristian@gmail.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('23251316Dilan');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Catalogos' }).click();
  await expect(page.getByRole('img', { name: 'Camiseta azul' })).toBeVisible();
  await expect(page.getByText('Camiseta azul')).toBeVisible();
  await expect(page.getByText('₡ 2,000')).toBeVisible();
  await expect(page.getByRole('button', { name: '🛒 Agregar al carrito' }).nth(2)).toBeVisible();
  await page.getByRole('textbox', { name: 'Buscar producto por nombre...' }).click();
  await page.getByRole('textbox', { name: 'Buscar producto por nombre...' }).fill('Camiseta azul');
  await expect(page.getByText('Camiseta azul')).toBeVisible();
  await page.getByRole('textbox', { name: 'Buscar producto por nombre...' }).click();
  await page.getByRole('textbox', { name: 'Buscar producto por nombre...' }).fill('');
  await page.getByRole('combobox').first().selectOption('HomeAccessories');
  await expect(page.getByText('Organizador de madera')).toBeVisible();
  await page.getByRole('combobox').first().selectOption('');
  await page.getByRole('combobox').nth(1).selectOption('M');
  await expect(page.getByText('Camiseta azul')).toBeVisible();
  await page.getByRole('combobox').nth(1).selectOption('');
  await page.getByRole('textbox', { name: 'Color' }).click();
  await page.getByRole('textbox', { name: 'Color' }).fill('Azul');
  await expect(page.getByText('Camiseta azul')).toBeVisible();
  await page.getByRole('textbox', { name: 'Color' }).click();
  await page.getByRole('textbox', { name: 'Color' }).fill('');
  await page.getByRole('textbox', { name: 'Material' }).click();
  await page.getByRole('textbox', { name: 'Material' }).fill('Algodón');
  await expect(page.getByText('Camiseta azul')).toBeVisible();
  await page.getByRole('textbox', { name: 'Material' }).click();
  await page.getByRole('textbox', { name: 'Material' }).fill('');
  await page.getByPlaceholder('Min ₡').click();
  await page.getByPlaceholder('Min ₡').fill('1000');
  await page.getByPlaceholder('Max ₡').click();
  await page.getByPlaceholder('Max ₡').fill('3000');
  await expect(page.getByText('Camiseta azul')).toBeVisible();
});