import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('dilan@gmail.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('23251316Dilan');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByText('Productos').click();
  await page.getByRole('button', { name: 'Agregar producto' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).click();
  await page.getByRole('textbox', { name: 'Nombre' }).fill('Camisa amarilla');
  await page.getByRole('textbox', { name: 'Descripción' }).click();
  await page.getByRole('textbox', { name: 'Descripción' }).fill('camisa amarilla');
  await page.getByRole('textbox', { name: 'Color' }).click();
  await page.getByRole('textbox', { name: 'Color' }).fill('Amarilla');
  await page.getByRole('textbox', { name: 'Tipo de material' }).click();
  await page.getByRole('textbox', { name: 'Tipo de material' }).fill('Algodón');
  await page.getByRole('spinbutton', { name: 'Precio' }).click();
  await page.getByRole('spinbutton', { name: 'Precio' }).fill('1000');
  await page.getByRole('spinbutton', { name: 'Cantidad' }).click();
  await page.getByRole('spinbutton', { name: 'Cantidad' }).fill('10');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('CamisaRoja.jpg');
  await page.getByRole('textbox', { name: 'Talla' }).click();
  await page.getByRole('textbox', { name: 'Talla' }).fill('M');
  await page.getByRole('textbox', { name: 'Tipo de ropa' }).click();
  await page.getByRole('textbox', { name: 'Tipo de ropa' }).fill('nada');
  await page.getByLabel('Género').selectOption('Masculino');
  await page.getByRole('button', { name: 'Guardar producto' }).click();
  await page.getByRole('button', { name: 'Sí' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByRole('button', { name: 'Eliminar' }).nth(3).click();
  await expect(page.getByRole('heading', { name: '¿Eliminar producto?' })).toBeVisible();
  await expect(page.getByText('¿Seguro que deseas eliminar "')).toBeVisible();
  await page.getByRole('button', { name: 'Sí' }).click();
  await expect(page.getByRole('heading', { name: 'Eliminado' })).toBeVisible();
  await expect(page.getByText('Producto eliminado')).toBeVisible();
  await page.getByRole('button', { name: 'Aceptar' }).click();
});