import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:5173/login');
  await page.locator('input[type="email"]').click();
  await page.locator('input[type="email"]').fill('dilan@gmail.com');
  await page.locator('input[type="password"]').click();
  await page.locator('input[type="password"]').fill('23251316Dilan');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await page.getByText('Usuarios').click();
  await page.getByRole('button', { name: 'Editar' }).nth(1).click();
  await page.waitForLoadState("domcontentloaded")
  await expect(page.locator('input[name="name"]')).toBeVisible();
  await expect(page.locator('input[name="lastName"]')).toBeVisible();
  await expect(page.locator('h2')).toContainText('Editar Usuario');
  await expect(page.locator('input[name="name"]')).toHaveValue('Dilan');
  await expect(page.locator('input[name="lastName"]')).toHaveValue('Flores');
  await expect(page.locator('input[name="birthDay"]')).toHaveValue('2005-05-22');
  await expect(page.locator('input[name="phoneNumber"]')).toHaveValue('88888888');
  await expect(page.locator('select[name="gender"]')).toHaveValue('Masculino');
  await expect(page.getByRole('combobox').nth(1)).toHaveValue('Limón');
  await expect(page.getByRole('combobox').nth(2)).toHaveValue('Pococí');
  await expect(page.getByRole('combobox').nth(3)).toHaveValue('Rita');
  await expect(page.locator('input[name="exactAddress"]')).toHaveValue('Casa amarilla');
  await page.locator('input[name="lastName"]').click();
  await page.locator('input[name="lastName"]').fill('Flores Martinez');
  await page.locator('input[name="birthDay"]').fill('2005-05-21');
  await page.locator('input[name="phoneNumber"]').click();
  await page.locator('input[name="phoneNumber"]').fill('88888887');
  await page.getByRole('combobox').nth(1).selectOption('San José');
  await page.getByRole('combobox').nth(2).selectOption('Mora');
  await page.getByRole('combobox').nth(3).selectOption('Guayabo');
  await page.locator('input[name="exactAddress"]').click();
  await page.locator('input[name="exactAddress"]').fill('Casa verde');
  await page.getByRole('button', { name: 'Guardar' }).click();
  await expect(page.getByRole('heading', { name: '¿Guardar cambios?' })).toBeVisible();
  await expect(page.getByText('¿Está seguro que quiere')).toBeVisible();
  await page.getByRole('button', { name: 'Sí' }).click();
  await expect(page.getByRole('heading', { name: 'Actualizado' })).toBeVisible();
  await expect(page.getByText('Se realizaron los cambios')).toBeVisible();
  await page.getByRole('button', { name: 'Aceptar' }).click();
  await expect(page.getByRole('cell', { name: 'Flores Martinez' })).toBeVisible();
  await expect(page.getByRole('cell', { name: '21/05/' })).toBeVisible();
  await page.getByRole('button', { name: 'Ver dirección' }).nth(1).click();
  await expect(page.getByText('Provincia: San José')).toBeVisible();
  await expect(page.getByText('Cantón: Mora')).toBeVisible();
  await expect(page.getByText('Distrito: Guayabo')).toBeVisible();
  await expect(page.getByText('Dirección exacta: Casa verde')).toBeVisible();
  await page.getByRole('button', { name: 'Cerrar' }).click();
  await page.getByRole('button', { name: 'Editar' }).nth(1).click();
  await page.waitForTimeout(2000);
  await page.locator('input[name="lastName"]').click();
  await page.locator('input[name="lastName"]').fill('Flores');
  await page.waitForTimeout(2000);
  await page.locator('input[name="birthDay"]').fill('2005-05-22');
  await page.locator('input[name="phoneNumber"]').click();
  await page.locator('input[name="phoneNumber"]').fill('88888888');
  await page.getByRole('combobox').nth(1).selectOption('Limón');
  await page.getByRole('combobox').nth(2).selectOption('Pococí');
  await page.getByRole('combobox').nth(3).selectOption('Rita');
  await page.locator('input[name="exactAddress"]').click();
  await page.locator('input[name="exactAddress"]').fill('Casa amarilla');
  await page.getByRole('button', { name: 'Guardar' }).click();
  await page.getByRole('button', { name: 'Sí' }).click();
  await page.getByRole('button', { name: 'Aceptar' }).click();
});